name: Check with rzk

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    name: Check formalisations with rzk proof assistant
    steps:
      - uses: actions/checkout@v3

      - name: Check all files
        uses: fizruk/rzk-action@v1
        with:
          files: src/hott/* src/simplicial-hott/*
